<?php

namespace IMAG\PhdCallBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhdUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhdUserRepository extends EntityRepository
{
    public function userIdHavePhdId($userId, $phdId)
    {
        $q = $this->createQueryBuilder('pu')
            ->select('pu')
            ->where('pu.user = ?1')
            ->andWhere('pu.phd = ?2')
            ->setParameters(array(
                1 => $userId,
                2 => $phdId
            ))
            ->getQuery()
            ;

        return $q->getOneOrNullResult();
    }
}