<?php

namespace IMAG\PhdCallBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhdUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhdUserRepository extends EntityRepository
{
    public function userHavePhd(\IMAG\PhdCallBundle\Entity\User $user, \IMAG\PhdCallBundle\Entity\Phd $phd)
    {
        $q = $this->createQueryBuilder('pu')
            ->select('pu')
            ->where('pu.user = :user')
            ->andWhere('pu.phd = :phd')
            ->setParameters(array(
                'user' => $user,
                'phd'  => $phd
            ))
            ->getQuery()
            ;

        return $q->getOneOrNullResult();
    }
}